version: '3.7'

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data/data:/var/lib/postgresql/data/
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - db
      - rabbitmq
      - worker
    links:
      - db
      - rabbitmq
      - worker
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    stdin_open: true
  rabbitmq:
    build:
      context: ./rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
      - 25672:25672
  worker:
    build:
      context: ./celery
      dockerfile: Dockerfile-celery-worker
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
